### ISSUE TITLE
container weight

### ISSUE THREAD

**Issue by JWKnapp** [xrnm/odnd-character-sheet#34]
containers add their own weight to the total their carrying (if this is as intended, we can delete this issue)

**Comment by xrnm** [comment]
Items listed on the container card reflect the contents and capacity of the container. Total container weight including contents and container itself are reflected on the line item for the container.

Ie a quarrel case with 30 bolts init would show

Slung Items:
  Quarrel Case 40cn

Quarrel Case
30cn/30cn

Double check me, but I think we can close this.

**Comment by JWKnapp** [comment]
yep you are correct. containers look good.
