### ISSUE TITLE
Item management (drag and drop)

### ISSUE THREAD

**Issue by JWKnapp** [xrnm/odnd-character-sheet#38]
take similar concept from spells and allow users to drag and drop items from one container to another (or into storage {see ticket #37 })

**Comment by xrnm** [comment]
This is already implemented AFAIK. All inventory and animal assets are drag/dropable. The only shortcoming is that currently containers cannot contain containers.

**Comment by xrnm** [comment]
Which was requested in #8

**Comment by xrnm** [comment]
Closing ticket since I believe this is already how it works
