### ISSUE TITLE
Quick Reference Bar - User Feedback/Feature Request

### ISSUE THREAD

**Issue by TemlinTook** [xrnm/odnd-character-sheet#42]
I think it would be beneficial if there were a fixed area at the top of the page (under the Nav Bar) which showed Name, Class, Level, Ability data, and possibly saving throw data.  

This would allow users to navigate to other sections of their character sheets and perform tasks like Inventory Management and note taking while easily referencing any pertinent stats they would need. A simple text line (WARRIOR THE FIGHTER | L:3 | STR:12+1 | INT:10 | WIS:8 | etc.) would be great for this.

**Comment by xrnm** [comment]
I like this idea a lot actually. I'm always scrolling/navigating back to the character section when on the adventure log and other pages.

Feature requested!
