### ISSUE TITLE
XP Logging Issue/Clarification

### ISSUE THREAD

**Issue by TemlinTook** [xrnm/odnd-character-sheet#44]
When adding XP from the Experience section of the Log page, the bonus is not shown.  I'm not sure if this is intentional or not. 

It appears that there is a difference in the way the process takes place. 

On the character page,, when you click the purple + it opens a new dialog box which correctly shows the bonus across the bottom.  You then click done and it records the experience with the bonus.  

On the log page, clicking the purple + automatically adds an entry into the Experience section, with no dialog box opening.  Opening then entry does not show the bonus experience area at the bottom.  Entering the experience in this section does show in the Experience Block on the Character Sheet, but only the entered amount, not the bonus adjusted amount.

**Comment by xrnm** [comment]
Thanks for the note. I assumed they used the same dialog but I did not test it out.

I will update the adventure log to use the same experience add dialog.
