### ISSUE TITLE
Feature Request - Fixed Header/Nav Bar

### ISSUE THREAD

**Issue by TemlinTook** [xrnm/odnd-character-sheet#51]
Now that you have so masterfully created that quick stats bar, I think it would be great if it and the navigation were anchored to the top of the page so that they never moved, regardless of scrolling.

**Comment by xrnm** [comment]
I like that idea, but I may want to shrink it a bit for different screen sizes. Might be something @JWKnapp could look at. If not I'll get to it when life slows down a bit.
