### ISSUE TITLE
Ability Scores adjusted by Primary Ability not granting correct bonuses

### ISSUE THREAD

**Issue by ameer-bauer** [xrnm/odnd-character-sheet#54]
Hiya,

The bonuses derived from Ability Score + Prime are not rendering properly if the character levels up and the Prime adjustment is high enough to grant a bonus.  _E.g. a Level 4 Fighter with a base Ability Score of 10 STR should have a +1 to Melee Damage. (since 10 + 4 = 14)_

This seems to be consistent across all of the Ability Scores.  Thanks for looking into this issue, keep up the great work! :D

**Comment by xrnm** [comment]
Hey Ameer,

I thought I had confirmed this with you so let me make sure I understand.

Ability Adjustments are calculated using adjusted score and not the base score? IE, if I am a magic user with a base int of 10 for every level I gain as a magic user I gain an additional language slot?

**Comment by ameer-bauer** [comment]
Hi Justin,

That is correct... it's designed to give a little bit more dynamic growth
to the characters.

Cheers.
-Ameer

**Comment by ameer-bauer** [comment]
...

Cheers.
-Ameer

**Comment by xrnm** [comment]
This is patched up to the ICS prod site.

Sorry for my mistake and a potentially huge issue.

**Comment by ameer-bauer** [comment]
Haha, no worries, no huge issues at all!  I appreciate all the awesome work
on ics. :)

Cheers.
-Ameer
