### ISSUE TITLE
Feature Request - Dropping Backpack

### ISSUE THREAD

**Issue by mterrasi** [xrnm/odnd-character-sheet#59]
The ICS is looking great! I think it might be helpful if there was the ability to un-equip or drop a backpack temporarily, without deleting it and all of its contents. Either by adding a minus button like with the items in the backpack, that would then strikethrough all of the items leaving them there to be added back, with a plus button that caps at 1. Or instead of plus and minus buttons there could be a box next to the backpack to check to un-equip. That way you could see your character's new weight and encumbrance rating if you were to leave or drop your backpack.

**Comment by xrnm** [comment]
Yeah! This is a great idea. It duplicates #39 so I'm going to close it out.
