### ISSUE TITLE
Feature Request - Identifier for dropped items

### ISSUE THREAD

**Issue by mterrasi** [xrnm/odnd-character-sheet#62]
Hey Justin,
The drop items feature is awesome! I think it's great that you can drop an item without reducing the number listed on the item (on torches for example) to zero and that when dropping a slung item, the items inside are not struck-through, that way you can still access the items, even if the container itself is not equipped. One thought to build on this feature though, would be to add an identifier to the associated card for slung items, letting you know that the container is not currently equipped. A possible solution could be to have a small italicized "unequipped" show up under the title of the slung item's card.

**Comment by xrnm** [comment]
Love the idea! I noticed looking into this that I'm not accounting for slung item weights too. Let me get a fix out for this.
